extraction:
  cpp:
    after_prepare: 
      - python report.py 42
  cobol:
    after_prepare: 
      - python report.py 42
  csharp:
    after_prepare: 
      - python report.py 42
  java:
    after_prepare: 
      - python report.py 42
  javascript:
    after_prepare: 
      - python report.py 42
  python:
    after_prepare: 
      - python report.py 42
